#!/bin/env bash
# prints words based on the number x

x=0
while [ $x -le 9 ]
do
if [ $x -eq 4 ]
then
echo "bad luck"

elif [ $x -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
x=$(( $x + 1))
done