#!/bin/env bash
# prints minutes and hours

minute=0
hour=0
echo "Hour: $hour"
while [ $hour -le 12 ]
do
echo $minute
if [ $minute -eq 59 ]
then
   hour=$(( $hour + 1 ))
   minute=0
   if [ $hour -ne 13 ]
   then
	echo "Hour: $hour"
   fi
fi
minute=$(( $minute + 1 ))
done